services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: jet
      POSTGRES_PASSWORD: Toxik666
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:11111
    volumes:
      - .:/app
    ports:
      - "11111:11111"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://jet:Toxik666@db:5432/mydb
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - "*.pyc"
            - "__pycache__/"

volumes:
  postgres_data:
